---

- name: get updater name
  local_action: command git config user.name
  register: updater
  tags: slack

- name: send notification via Slack
  local_action:
    module: slack
    token: "{{ slack_notify.url }}"
#    channel: "{{ slack_notify.channel }}"
    msg: " :tada: *{{ server }}* has been updated with `{{ branch }}`"
    parse: "full"
    link_names: 1
  tags: slack
